#!/usr/bin/env node
import * as fs from "node:fs";
import * as path from "node:path";

import { z } from "zod";

/**
 * `create-harpua-app` — scaffolds a runnable NestJS + LangGraph weather agent.
 *
 *   pnpm create harpua-app my-agent
 *   npx create-harpua-app my-agent
 *
 * It copies the embedded `template/` directory into a new project directory,
 * names the project after the target directory's basename, and prints the next
 * steps. Node stdlib + zod only — no network, no other dependencies.
 */

/**
 * A generated project name is the target directory's basename; it becomes the
 * scaffolded `package.json` `name`, so it must be an npm-installable, unscoped
 * package name. Validated (not hand-rolled) so a bad directory name fails with
 * a clear message instead of producing an uninstallable project.
 */
const appNameSchema = z
  .string()
  .min(1, "project name must not be empty")
  .max(214, "project name must be 214 characters or fewer")
  .regex(
    /^[a-z0-9][a-z0-9._-]*$/,
    "project name must be lowercase and url-safe (letters, digits, '.', '_', '-'), starting with a letter or digit",
  );

/**
 * Directories that must never be copied out of the template, even if a local
 * verification run left them behind. Build output and installed deps are
 * regenerated by the scaffolded project's own `pnpm install` / `pnpm build`.
 */
const SKIP_ENTRIES = new Set(["node_modules", "dist", ".turbo", "coverage"]);

/**
 * npm strips or repurposes a `.gitignore` inside a published tarball, so the
 * template stores it WITHOUT the leading dot and we restore the dot on copy.
 * This is the classic create-app trap.
 */
const GITIGNORE_SOURCE = "gitignore";
const GITIGNORE_TARGET = ".gitignore";

export interface ScaffoldOptions {
  /** Absolute path of the project directory to create. */
  targetDir: string;
  /** Absolute path of the `template/` directory to copy from. */
  templateDir: string;
}

export interface ScaffoldResult {
  targetDir: string;
  /** The derived, validated project (package) name. */
  appName: string;
  /** Relative paths of every file written into the target, sorted. */
  files: string[];
}

/** Thrown for user-actionable failures (bad name, non-empty target). */
export class ScaffoldError extends Error {}

function isNonEmptyDir(dir: string): boolean {
  try {
    return fs.readdirSync(dir).length > 0;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw err;
  }
}

/**
 * Recursively copy `from` to `to`, renaming `gitignore` -> `.gitignore` and
 * skipping build/dependency directories. Returns the relative paths written.
 */
function copyTree(from: string, to: string, relBase = ""): string[] {
  const written: string[] = [];
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    if (SKIP_ENTRIES.has(entry.name)) continue;
    const targetName =
      entry.name === GITIGNORE_SOURCE ? GITIGNORE_TARGET : entry.name;
    const srcPath = path.join(from, entry.name);
    const destPath = path.join(to, targetName);
    const rel = path.join(relBase, targetName);
    if (entry.isDirectory()) {
      written.push(...copyTree(srcPath, destPath, rel));
    } else {
      fs.copyFileSync(srcPath, destPath);
      written.push(rel);
    }
  }
  return written;
}

/** Rewrite the scaffolded `package.json` `name` to the derived project name. */
function setPackageName(targetDir: string, appName: string): void {
  const pkgPath = path.join(targetDir, "package.json");
  const pkg = z
    .object({ name: z.string() })
    .passthrough()
    .parse(JSON.parse(fs.readFileSync(pkgPath, "utf8")));
  pkg.name = appName;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
}

/**
 * Scaffold a new project. Refuses a non-empty existing target, validates the
 * derived name, copies the template, and stamps the project name.
 */
export function scaffold(options: ScaffoldOptions): ScaffoldResult {
  const { targetDir, templateDir } = options;
  const appName = path.basename(targetDir);

  const parsed = appNameSchema.safeParse(appName);
  if (!parsed.success) {
    throw new ScaffoldError(
      `"${appName}" is not a valid project name: ${parsed.error.issues[0]?.message}. ` +
        `Pick a target directory whose name is a valid npm package name.`,
    );
  }

  if (isNonEmptyDir(targetDir)) {
    throw new ScaffoldError(
      `Target directory "${targetDir}" already exists and is not empty. ` +
        `Choose a new directory or empty this one first.`,
    );
  }

  const files = copyTree(templateDir, targetDir).sort();
  setPackageName(targetDir, appName);

  return { targetDir, appName, files };
}

function nextSteps(result: ScaffoldResult): string {
  const rel = path.relative(process.cwd(), result.targetDir) || ".";
  return [
    "",
    `Scaffolded ${result.appName} into ${result.targetDir}`,
    "",
    "Next steps:",
    `  cd ${rel}`,
    "  pnpm install       # links the agent skills via the prepare script",
    "  pnpm start:dev     # boot the API on :3000 (or: pnpm chat for the CLI)",
    "",
    'Then: curl -XPOST localhost:3000/agent/t1 -H "content-type: application/json" \\',
    `        -d '{"message":"what is the weather in berlin?"}'`,
    "",
    "The default MODEL_PROVIDER is 'mock' (deterministic, offline-friendly, but it still",
    "calls the real Open-Meteo API for weather). Go real with OpenRouter — one key,",
    "every model: MODEL_PROVIDER=openrouter OPENROUTER_API_KEY=... OPENROUTER_MODEL=...",
    "(or ollama / openai-compatible) — see the README.",
    "",
  ].join("\n");
}

/* istanbul ignore next -- bin entry: thin caller, exercised by the pack smoke test */
export function main(argv: string[]): void {
  const targetArg = argv[2];
  if (!targetArg) {
    console.error("Usage: create-harpua-app <target-dir>");
    process.exit(1);
  }

  try {
    const result = scaffold({
      targetDir: path.resolve(process.cwd(), targetArg),
      templateDir: path.join(__dirname, "..", "template"),
    });
    console.log(nextSteps(result));
  } catch (err) {
    if (err instanceof ScaffoldError) {
      console.error(`create-harpua-app: ${err.message}`);
    } else {
      console.error(
        `create-harpua-app: failed to scaffold: ${(err as Error).message}`,
      );
    }
    process.exit(1);
  }
}

/* istanbul ignore next -- only runs as a bin, not when imported by tests */
if (require.main === module) {
  main(process.argv);
}
